#!/usr/bin/env python3
"""Writes the manifest ossia/score-packages points at.

Two different files are both called package.json, and they are not the same
thing:

  * the one *inside* the zip -- generated by CMake from package.json.in -- is
    what a user ends up with in ~/Documents/ossia/score/packages/depth-camera,
    and score overwrites it on install anyway;

  * this one is the *remote* manifest. score reads it over HTTP, looks up the
    key matching score::addonArchitecture() and downloads the zip it names.

They share their metadata, so this reads package.json.in rather than repeating
it, and adds one entry per architecture pointing at the release assets the
Package workflow just uploaded.

    make_manifest.py --tag v1.0 --repo ossia/score-addon-orbbec --out depth-camera.json
"""

import argparse
import json
import os
import re
import sys

# score::addonArchitecture() spells these exactly. The aliases are what other
# ossia packages carry for the same platform, kept so a score built against a
# boost that reports amd64 still finds a download.
ARCHITECTURES = {
    "linux-x86_64": ["linux-amd64"],
    "linux-aarch64": ["linux-arm64"],
    "darwin-x86_64": ["darwin-amd64"],
    "darwin-aarch64": ["darwin-arm64"],
    "windows-x86_64": ["windows-amd64"],
    "windows-aarch64": ["windows-arm64"],
}

HERE = os.path.dirname(os.path.abspath(__file__))


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--tag", required=True, help="release tag holding the assets")
    ap.add_argument("--repo", required=True, help="owner/name of the repository")
    ap.add_argument("--out", required=True)
    ap.add_argument("--template", default=os.path.join(HERE, "package.json.in"))
    ap.add_argument(
        "--size", default="35M", help="approximate installed size, shown in the UI"
    )
    args = ap.parse_args()

    with open(args.template, encoding="utf-8") as f:
        text = f.read()

    # The template is CMake's, so it still carries @SCORE_DEPTHCAM_ARCH@. Null
    # it out rather than substituting: a remote manifest describes every
    # architecture at once, so a single "architecture" field is meaningless here.
    text = re.sub(r"@[A-Z0-9_]+@", "", text)
    manifest = json.loads(text)
    manifest.pop("architecture", None)

    manifest["size"] = args.size

    base = f"https://github.com/{args.repo}/releases/download/{args.tag}"
    for arch, aliases in ARCHITECTURES.items():
        url = f"{base}/depth-camera-{arch}.zip"
        for key in [arch] + aliases:
            manifest[key] = url

    # score reads "version" with QJsonValue::toInt(): a string, or a float like
    # 1.1, silently becomes 0 and every install then looks like a downgrade.
    if not isinstance(manifest.get("version"), int):
        print(
            f"error: version must be an integer, got {manifest.get('version')!r}",
            file=sys.stderr,
        )
        return 1

    with open(args.out, "w", encoding="utf-8") as f:
        json.dump(manifest, f, indent=2)
        f.write("\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
